# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - client/node_modules/
  - utility/node_modules/
  - server/node_modules/

stages:
 - build
 - test
 - cleanup

build:utility:
  stage: build
  script:
    - cd utility/
    - make setup-dev build

build:client:
  stage: build
  script:
    - cd client/
    - make setup-dev build

build:server:
  stage: build
  script:
    - cd server/
    - make setup-dev build

test:utility:
  stage: test
  script:
   - cd utility/
   - make test

test:client:
  stage: test
  script:
   - cd client/
   - make test

cleanup:utility:
  stage: cleanup
  script:
    - cd utility/
    - make clean
  when: always

cleanup:client:
  stage: cleanup
  script:
    - cd client/
    - make clean
  when: always

cleanup:server:
  stage: cleanup
  script:
    - cd server/
    - make clean
  when: always
